src/AppBundle/Entity/Grados.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Grados
 *
 * @ORM\Table(name="grados")
 * @ORM\Entity
 */
class Grados
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="GradoNombre", type="string", length=45, nullable=false)
     */
    private $gradonombre;

public function __toString(){
    return (string) $this->getgradonombre();
}


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set gradonombre
     *
     * @param string $gradonombre
     *
     * @return Grados
     */
    public function setGradonombre($gradonombre)
    {
        $this->gradonombre = $gradonombre;

        return $this;
    }

    /**
     * Get gradonombre
     *
     * @return string
     */
    public function getGradonombre()
    {
        return $this->gradonombre;
    }
    public function getNombre()
    {
        return $this->gradonombre;
    }
}

src/AppBundle/Resources/views/Reporte/base_reporte.html.twig
{#

This file is part of the Sonata package.

(c) Thomas Rabaix <thomas.rabaix@sonata-project.org>

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

#}

{% extends base_template %}

{% block title %}
    {# NEXT_MAJOR: remove default filter #}
    {% if objectId|default(admin.id(object)) is not null %}
        {{ "title_edit"|trans({'%name%': admin.toString(object)|truncate(15) }, 'SonataAdminBundle') }}
    {% else %}
        {{ "title_create"|trans({}, 'SonataAdminBundle') }}
    {% endif %}
{% endblock %}

{% block navbar_title %}
    {{ block('title') }}
{% endblock %}

{%- block actions -%}{%- endblock -%}

{% block tab_menu %}{{ knp_menu_render(admin.sidemenu(action), {'currentClass' : 'active', 'template': sonata_admin.adminPool.getTemplate('tab_menu_template')}, 'twig') }}{% endblock %}

{% use 'AppBundle:Reporte:base_reporte_form.html.twig' with form as parentForm %}

{% block form %}
    {{ block('parentForm') }}
{% endblock %}

src/AppBundle/Resources/views/Reporte/reporte_agrupaciones.html.twig
{% if datos %}
    <div class="box box-primary">
        <div id="chart_div" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
        <table class="table table-bordered table-responsive table-striped" style="max-width: 60%; margin:auto;">
            <tbody>
            {% set total = 0 %}
            {% for entidad,valores in datosParaTabla %}
                <tr>
                    <td colspan="2" style="width: 50%" class="text-center">
                        {{ labels[entidad] }}
                    </td>
                </tr>
                {% set totalParcial = 0 %}
                {% for campo,valor in valores %}
                    {% if valor != 0 %}
                    <tr>
                        <td>
                            {{ campo }}
                        </td>
                        <td>
                            {{ valor }}
                            {% set total = total + valor %}
                            {% set totalParcial = totalParcial + valor %}
                        </td>
                    </tr>
                    {% endif %}
                {% endfor %}
                <tr>
                    <td><b>Total {{ labels[entidad] }}</b></td>
                    <td><b>{{ totalParcial }}</b></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <br>
    </div>
    <script type="text/javascript">

        Highcharts.chart('chart_div', {
            chart: {
                type: 'column'
            },
            title: {
                text: 'Grafica por agrupaciones'
            },
            xAxis: {
                categories: [
                    {% for entidad , categorias in columnas %}
                    '{{ entidad }}'{%- if not loop.last %},{% endif -%}
                    {% endfor %}
                ]
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Total de solicitudes'
                },
                stackLabels: {
                    enabled: true,
                    style: {
                        fontWeight: 'bold',
                        color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                    }
                }
            },
            legend: false,
            tooltip: {
                headerFormat: '<b>{point.x}</b><br/>',
                pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
            },
            plotOptions: {
                column: {
                    stacking: 'normal',
                    dataLabels: {
                        enabled: true,
                        color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white'
                    }
                }
            },
            series: [
                {% for categoria , dato in datos %}
                {
                    name: '{{ categoria }}',
                    data:{{ dato|json_encode|raw }}

                }{%- if not loop.last %},{% endif -%}
                {% endfor %}

            ]
        });
    </script>

{% else %}
    <div>No se encontró información con los parametros de busqueda.</div>
{% endif %}

src/AppBundle/Resources/views/Reporte/reporte_cantidades.html.twig
{%if datos %}
    <style>
        .titulo{
            height: 40px; 
            background-color: #5AC7FF;
        }
        .elemento1{
            background-color: gray;
            height: 20px; 
        }
        .elemento2{
            height: 20px; 
            background-color: white;
        }
    </style>
    <br>
    <br>
    <div class="text-center" id="chart_div"></div>
    <br>
    <br>
    <div class="col-md-12">
        <div class="col-md-2"></div>
        <div class="col-md-8 text-center">
            <div class="col-md-6 titulo">Seccional</div>
            <div class="col-md-2 titulo">Radicadas</div>
            <div class="col-md-2 titulo">Aprobadas</div>
            <div class="col-md-2 titulo">Rechazadas</div>
            {%set cuenta = 1%}
            {%set total = 0%}
            {%set aprobadas = 0%}
            {%set rechazadas = 0%}
            {%for key, dato in datos%}
                {%set total = total + dato.total%}
                {%set aprobadas = aprobadas + dato.aprobadas%}
                {%set rechazadas = rechazadas + dato.rechazadas%}
                <div class="col-md-6 {% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{key}}</div>
                <div class="col-md-2 {% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{dato.total}}</div>
                <div class="col-md-2 {% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{dato.aprobadas}}</div>
                <div class="col-md-2 {% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{dato.rechazadas}}</div>
                {%set cuenta = cuenta +1 %}
            {%endfor%}
            <div class="col-md-6 titulo">Total</div>
            <div class="col-md-2 titulo">{{total}}</div>
            <div class="col-md-2 titulo">{{aprobadas}}</div>
            <div class="col-md-2 titulo">{{rechazadas}}</div>
        </div>
        <div class="col-md-2"></div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <script type="text/javascript">
        var myData = new Array(
                {%for k, registro in datos%}
                    {%if k == (datos|length -1)%}
                        ['{{k}}', {{registro.total}}, {{registro.aprobadas}}, {{registro.rechazadas}}]
                    {%else%}
                        ['{{k}}', {{registro.total}}, {{registro.aprobadas}}, {{registro.rechazadas}}],
                    {%endif%}
                {%endfor%}
                );
        var myChart = new JSChart('chart_div', 'bar');
        myChart.setDataArray(myData);
        myChart.setTitle('Cantidad de programas solicitados por seccional');
        myChart.setTitleColor('#3F779E');
        myChart.setAxisNameX('');
        myChart.setAxisNameY('');
        myChart.setAxisNameFontSize(16);
        myChart.setAxisNameColor('#999');
        myChart.setAxisValuesAngle(30);
        myChart.setAxisValuesColor('#777');
        myChart.setAxisColor('#000000');
        myChart.setAxisWidth(1);
        myChart.setBarValuesColor('#2F6D99');
        myChart.setAxisPaddingTop(60);
        myChart.setAxisPaddingBottom(60);
        myChart.setAxisPaddingLeft(45);
        myChart.setTitleFontSize(11);
        myChart.setBarColor('#3F779E', 1);
        myChart.setBarColor('#036C2A', 2);
        myChart.setBarColor('#FF0000', 3);
        myChart.setBarBorderWidth(0);
        myChart.setBarSpacingRatio(50);
        myChart.setBarOpacity(0.9);
        myChart.setFlagRadius(6);
        myChart.setTooltipPosition('nw');
        myChart.setTooltipOffset(3);
        myChart.setLegendShow(true);
        myChart.setLegendPosition('right top');
        myChart.setLegendForBar(1, 'Radicadas');
        myChart.setLegendForBar(2, 'Aprobadas');
        myChart.setLegendForBar(3, 'Rechazadas');
        myChart.setSize(616, 321);
        myChart.setGridColor('#C6C6C6');
        myChart.draw();
        
    </script>

{%else%}
    <div>No se encontró información con los parametros de busqueda.</div>
{%endif%}

src/AppBundle/Resources/views/Reporte/reporte_general.html.twig
{%if datos %}
    <style>
        .titulo{
            height: 40px; 
            background-color: #5AC7FF;
        }
        .elemento1{
            background-color: gray;
            height: 20px; 
        }
        .elemento2{
            height: 20px; 
            background-color: white;
        }
    </style>
    <br>
    <br>
    <div class="text-center" id="chart_div"></div>
    <br>
    <br>
    <div class="col-md-12">
        <div class="col-md-2"></div>
        <div class="col-md-8 text-center">
            <div class="col-md-6 titulo">{{columna}}</div>
            <div class="col-md-2 titulo">Radicadas</div>
            <div class="col-md-2 titulo">Aprobadas</div>
            <div class="col-md-2 titulo">Rechazadas</div>
            {%set cuenta = 1%}
            {%set total = 0%}
            {%set aprobadas = 0%}
            {%set rechazadas = 0%}
            {%for key, dato in datos%}
                {%set total = total + dato.total%}
                {%set aprobadas = aprobadas + dato.aprobadas%}
                {%set rechazadas = rechazadas + dato.rechazadas%}
                <div class="col-md-6 {% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{key}}</div>
                <div class="col-md-2 {% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{dato.total}}</div>
                <div class="col-md-2 {% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{dato.aprobadas}}</div>
                <div class="col-md-2 {% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{dato.rechazadas}}</div>
                {%set cuenta = cuenta +1 %}
            {%endfor%}
            <div class="col-md-6 titulo">Total</div>
            <div class="col-md-2 titulo">{{total}}</div>
            <div class="col-md-2 titulo">{{aprobadas}}</div>
            <div class="col-md-2 titulo">{{rechazadas}}</div>
        </div>
        <div class="col-md-2"></div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <script type="text/javascript">
        function decodeEntities(encodedString) {
            var textArea = document.createElement('textarea');
            textArea.innerHTML = encodedString;
            return textArea.value;
        }
        var myData = new Array(
        {%for k, registro in datos%}
            {%if k == (datos|length -1)%}
                        [decodeEntities('{{k}}'), {{registro.total}}, {{registro.aprobadas}}, {{registro.rechazadas}}]
            {%else%}
                [decodeEntities('{{k}}'), {{registro.total}}, {{registro.aprobadas}}, {{registro.rechazadas}}],
            {%endif%}
        {%endfor%}
                    );
            var myChart = new JSChart('chart_div', 'bar');
            myChart.setDataArray(myData);
            myChart.setTitle('Cantidad de programas solicitados por {{columna}}');
            myChart.setTitleColor('#3F779E');
            myChart.setAxisNameX('');
            myChart.setAxisNameY('');
            myChart.setAxisNameFontSize(16);
            myChart.setAxisNameColor('#999');
            myChart.setAxisValuesAngle(30);
            myChart.setAxisValuesColor('#777');
            myChart.setAxisColor('#000000');
            myChart.setAxisWidth(1);
            myChart.setBarValuesColor('#2F6D99');
            myChart.setAxisPaddingTop(60);
            myChart.setAxisPaddingBottom(60);
            myChart.setAxisPaddingLeft(45);
            myChart.setTitleFontSize(11);
            myChart.setBarColor('#3F779E', 1);
            myChart.setBarColor('#036C2A', 2);
            myChart.setBarColor('#FF0000', 3);
            myChart.setBarBorderWidth(0);
            myChart.setBarSpacingRatio(50);
            myChart.setBarOpacity(0.9);
            myChart.setFlagRadius(6);
            myChart.setTooltipPosition('nw');
            myChart.setTooltipOffset(3);
            myChart.setLegendShow(true);
            myChart.setLegendPosition('right top');
            myChart.setLegendForBar(1, 'Radicadas');
            myChart.setLegendForBar(2, 'Aprobadas');
            myChart.setLegendForBar(3, 'Rechazadas');
            myChart.setSize(616, 321);
            myChart.setGridColor('#C6C6C6');
            myChart.draw();

    </script>

{%else%}
    <div>No se encontró información con los parametros de busqueda.</div>
{%endif%}

src/AppBundle/Resources/views/Reporte/reporte_inscritos.html.twig
{%if datos %}
    <style>
        .titulo{
            height: 40px; 
            background-color: #5AC7FF;
        }
        .elemento1{
            background-color: gray;
            height: 20px; 
        }
        .elemento2{
            height: 20px; 
            background-color: white;
        }
    </style>
    <div class="col-md-12">
        <br>
        <br>
        <table class="text-center">
            <tr>
            <th class="titulo">Cuenta</th>
            <th class="titulo">Titular</th>
            <th class="titulo">Beneficiario</th>
            <th class="titulo">Seccional</th>
            </tr>
            {%set cuenta = 1%}
            {%for key, dato in datos%}
                {%for beneficiario in dato.beneficiarios%}
            <tr>
                    <td class="{% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{cuenta}}</td>
                    <td class="{% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{key}}</td>
                    <td class="{% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{beneficiario.nombre[0]}}</td>
                    <td class="{% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{beneficiario.seccional[0]}}</td>
            </tr>
                    {%set cuenta = cuenta +1 %}
                {%endfor%}
            {%endfor%}
        </table>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{%else%}
    <div>No se encontró información con los parametros de busqueda.</div>
{%endif%}

src/AppBundle/Resources/views/Reporte/reporte_movimientos.html.twig
{% if movimientos %}
    <style>
        .titulo {
            height: 40px;
            background-color: #5AC7FF;
        }

        .elemento1 {
            background-color: gray;
            height: 20px;
        }

        .elemento2 {
            height: 20px;
            background-color: white;
        }
    </style>
        <br>
        <br>
        <table class="text-center">
            <tr>
                <th class="titulo">Solicitante</th>
                <th class="titulo">Titular</th>
                <th class="titulo">Seccional</th>
                <th class="titulo">Área</th>
                <th class="titulo">Beneficio entregado</th>
            </tr>
            {% set cuenta = 1 %}
            {% for movimiento in movimientos %}
                <tr>

                    <td class="{% if cuenta is even %}elemento1{% else %}elemento2{% endif %}">{{ movimiento.concepto.solicitud.solicitudnombresolicita }}</td>
                    <td class="{% if cuenta is even %}elemento1{% else %}elemento2{% endif %}">{{ movimiento.concepto.solicitud.solicitudnombrefuncionario }}</td>
                    <td class="{% if cuenta is even %}elemento1{% else %}elemento2{% endif %}">{{ movimiento.seccional }}</td>
                    <td class="{% if cuenta is even %}elemento1{% else %}elemento2{% endif %}">{{ movimiento.presupuesto.idarea }}</td>
                    <td class="{% if cuenta is even %}elemento1{% else %}elemento2{% endif %}">{{ movimiento.valor }}</td>
                </tr>
                {% set cuenta = cuenta + 1 %}
            {% endfor %}
        </table>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{% else %}
    <div>No se encontró información con los parametros de busqueda.</div>
{% endif %}

src/AppBundle/Resources/views/Reporte/reporte_presupuesto.html.twig
{%if datos %}
    <style>
        .titulo{
            height: 40px; 
            background-color: #5AC7FF;
        }
        .elemento1{
            background-color: gray;
            height: 20px; 
        }
        .elemento2{
            height: 20px; 
            background-color: white;
        }
    </style>
    <div class="col-md-12">
        <br>
        <br>
        <div class="col-md-12 text-center">
            <div class="col-md-6 titulo">Programa</div>
            <div class="col-md-2 titulo">Monto</div>
            <div class="col-md-2 titulo">Saldo</div>
            <div class="col-md-2 titulo">Ejecutado</div>
            {%set cuenta = 1%}
            {%for key, dato in datos%}
                <div class="col-md-6 {% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{key}}</div>
                <div class="col-md-2 {% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{dato.monto}}</div>
                <div class="col-md-2 {% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{dato.saldo}}</div>
                <div class="col-md-2 {% if cuenta is even %}elemento1{%else%}elemento2{%endif%}">{{dato.monto - dato.saldo}}</div>
                {%set cuenta = cuenta + 1%}
            {%endfor%}
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
{%else%}
    <div>No se encontró información con los parametros de busqueda.</div>
{%endif%}